spring:
  datasource:
    url: jdbc:sqlite:data/fragments-instants.db?foreign_keys=on
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    enabled: true